# Limnic Subgroups for Histels 

[(4/6/20; PDF; 934 KB)](https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcseprd1569025&ext=pdf)

## Recommendation

**Recommendation:** Return to authors (date: 2020/06/09)

A precedent has been set for this with the recent nationally-accepted (2016) proposal from Tallyn, Thorson et al. extending L/coprogenous/Limnic to non-Histosols. The latest version of the 13th Edition keys (2020/03/17) reflects some changes to ensure that this broader usage of the subgroup is clear. The use of _coprogenous_ in the _Histels_ is, in principle, allowed if a _Limnic_ subgroup is defined -- which appears to be the main impetus for this proposal.

> Mineralogy Classes Applied Only to Limnic Subgroups: 
> Limnic materials (defined in chapter 3) with a thickness of 5 cm or more are mineralogy class criteria if the soil does not also have ferrihumic mineralogy. The following family classes are used: coprogenous, diatomaceous, and marly. 

Current wording in the key requires (criteria for) a Limnic subgroup (in the Histosols) in order to use a mineralogy class, so the criteria the authors have proposed (mirroring Histosols) make sense in that framework. However, it seems like the proposal was specifically focused on the _coprogenous_-Limnic variety of organic Gelisols.

I am not sure we have enough other examples in Histels with limnic materials that are _non-coprogenous_ to make a general change. While I have never worked in Alaska, I can imagine a variety of possible environments that could generate Limnic subgroups; some of which are not necessarily associated with the shoreline/avian coprogenous case detailed in the proposal. The marginal examples could have relatively little of this material (say, a few 1-2cm thick streaks) depending on the types of regular organic soil material and depositional environments they co-occur with. 

## On the relative difficulty of assessing cumulative >5cm thickness of limnic materials in Gelisols versus Histosols:

The cumulative >5cm thickness requirement is probably more difficult to assess in Histels compared to Histosols. As written criterion modeled after Histosols requires exposure of the _whole_ control section to know for sure that more or less than 5cm of limnic layers are present.

Their proposed criteria parity with the Histosols makes sense -- except for observation issues related to permafrost. This is, of course, the key difference between Histels and Histosols.

I am not sure that identification of the materials in marginal Limnic cases is as straightforward as suggested in the proposal (in lieu of lab data or really good exposure of the soil) – so this could turn into a bit of a materials identification problem.

## Suggestions

There could be value in having some sort of a mineralogy class to capture that extreme “eutrophic” case that we discussed on the call. 

I am empathetic to the field concerns about not being able to map this accurately to the subgroup level using remote methods. 

I think that these properties might be better addressed at the family level (in something like mineralogy class) rather than in more subgroup level taxa that could wind up being difficult or impractical to identify.

That way individuals who are interested / need to look at these soils in full detail have a framework to capture it but it doesn’t impose challenging-to-assess limitations on higher order classification of Gelisols. 
