# Simplify the Mollic Epipedon 

[(2/6/20; PDF; 278 KB)](https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcseprd1541215&ext=pdf)

## Recommendation

**Recommendation:** Return to authors (2020/03/31)

The proposed change to a simpler, non-sliding scale thickness would probably be good for the Mollisols concept. That said, simultaneous changes to thickness and materials criteria may dramatically shift concepts – and those potential shifts have not yet been thoroughly investigated. Too many moving parts in a single proposal hampers both proposer and reviewer ability to evaluate impacts. Therefore, I recommended this proposal be returned to the authors in the 2020 review.

Criteria changes for “mollic materials” – such as addition of pH measurements as surrogates for ammonium acetate base saturation, or changes to not-commonly-used color criteria, will need considerably more justification. 

Also, the authors do not address what, if any, changes would be made to harmonize the proposed Mollic definition with the existing definition of the Umbric. Revisions to this proposal should address intended changes to the Umbric. Is the intent to leave the Umbric unchanged? If so, that should be stated. This reviewer thinks that changes to requirements in Mollic, notably thickness, should be mirrored in the Umbric. I understand that it may be simpler to tackle just one for starters, but the long-term intent should be clear.

Review of specific changes proposed, by "Rule Number" in the proposed Mollic epipedon criteria.

## Opening Paragraph 

 * I fully support removing 18cm-mixing in favor of a more uniform depth criterion that does not involve mixing of any kind.

## Rule 1 

 * I work in an area of the world (California, Xeric SMR, Thermic STR) where Hard-setting Mollisols and would-be Mollisols exist. I generally do support the proposed logic here. While I agree with the intent, I think the potential correlation workload / impact on existing series is more significant than the proposal lets on.

  *	These hard-when-dry soils should be Mollisols if they meet all other criteria – the “growing season” for our annual grasses is before they set hard, and if they are irrigated the point is moot -- it generally behaves like a mollic if it has the carbon.

  *	I spoke briefly with Phil Smith (Soil Survey Leader in the MLRA 17 Soil Survey Office – CA Central Valley). Phil is far more knowledgeable than I on the Central Valley soils (MLRA 17) as well as those in MLRAs 14 and 15. He says that massive and hard when dry is a common occurrence in soils he encounters, and he would rather see them classify as Mollisols if other criteria are met. 
    
  *	Simple Example: Yolo series, MLRA 17 

   -	Fine-silty, mixed, superactive, nonacid, thermic Mollic Xerofluvents
      
   -	Range in Characteristics state “The surface is massive or platy and is hard or very hard.”
      
   -	Type location has 66cm of A horizon. Range in characteristics and typical pedon for A horizon state that mollic colors and carbon (OM 1.5-3%) are met. The typical pedon description reports a combined minimum thickness of ~17 inches or ~43cm for the A horizons – which is solidly greater than 25cm.
      
   -	Type location could go Pachic Haploxerolls with no fine stratification in epipedon and assuming carbon is met.
      
   - Presumably Xerofluvents have quite a bit of variation in them but a lot of that variation is in substratum -- basing off of type location and RIC – and the soils I have seen -- Yolo would become a Mollisol, and probably would be Pachic. Perhaps individual components/phases would be correlated differently/as taxadjuncts/to a new series. These are all decisions needing to be made at the Soil Survey Regional or MLRA office level.

 *	A very brief investigation of non-Mollisols-- including various Subgroups and Great Groups in Thermic STR and Xeric SMR -- turned up several series that could be impacted by the proposed changes to massive and hard criteria. I include a short list below – to be clear, I am not saying all of these would change – many are marginal on carbon content even with changes to structure and consistence. But they also often have limited data to support either Mollisol or non-Mollisol classification.

   *	Example Series: Tierra, Positas, Reiff, Jacinto, Honn, Keefers, Yokohl, Jahant, Sycamore, Zamora, Brentwood, Stomar, Camarillo, Hueneme, Pleasanton, Bellyspring

 *	To my knowledge, the slickest way to approach these questions is something like the PostgreSQL OSD full-text search created by Dylan Beaudette: http://soilmap2-1.lawr.ucdavis.edu/osd-search/, with those results then coupled with the fetchOSD function accessible through the soilDB R package – which provides facilities for accessing parsed OSD data for analysis

 *	The traditional way of doing this querying the SC database for specific taxa, and then text-mining the various sections of OSDs manually (or using soilDB). It is not clear that the authors did this – I would want to know what groups of soils they queried, and more specific examples of things they found. 

## Rule 2

 * Rock structure includes fine stratification. Epipedons, by definition (KST p 7, ST p 21), do not have rock structure.  

 * Therefore, the absence of rock structure is fundamental to what an epipedon is. 
  
  * Criteria 1c in proposed definition is unnecessary since “[in an epipedon] most of the rock structure [including fine stratification] has been destroyed.” If there are issues with current definition of rock structure, or its role in defining the epipedon, propose a change rather than working around the definition.
    
  * Suggestion: specifically encoding the rock structure <50% volume  (as opposed to “most”) value in epipedon definition would be a good change.

## Rule 3

 * These are rarely used criteria – and they add complexity -- but I think there needs to be more thorough investigation of where they may be used. Please explain the method the authors used to determine that the criteria “could not be verified if used in any existing soil series”.

  *	What analysis was done to verify these criteria were not used? What were the results? 
  
  *	Is there any way to simplify the wording, while retaining the same meaning? I am cautious about simultaneously changing thickness and materials criteria in same proposal.

## Rule 4 

  * I do not support the use of pH as a surrogate for base saturation as formal criteria. Dissimilar criteria, separated with an OR, results in perhaps unintentional equal weighting in determination of membership to a taxonomic class. 

  *	The authors did this analysis for all the KSSL data -- so they should have included a graph (like Appendix 2) of this data along with proposed thresholds. Most reviewers would not necessarily be able to thoroughly evaluate this proposal without at least some graphical representation

  *	The proposed pH thresholds are conservative in that they correspond with median pH by either method at ~80% ammonium acetate base saturation at pH 7 (Appendix 2. California KSSL data, upper 25cm mineral soil material [meeting organic carbon requirement]; n=916 pedons, 2043 horizons).  

  *	I think these surrogate criteria could result in more confusion – even though they are well protected against “false positives” for mollic as the data show.

  *	As proposed, 1:1 soil water and CaCl2 would be on equal footing, but use of both methods in parallel has not been adequately justified in proposal. 

  *	The proposed pH criteria cannot invert to identify Umbric; you would need conservatively _acidic_ thresholds in the Umbric criteria which would leave a pH-indeterminant area in the intermediate range say, pH ~5.5-6.5. We know this to be the case -- that the relationship is not as viable in that range.

  *	Protecting against false positive for Mollic epipedons leads to identification of more Umbric epipedons when color, organic carbon, thickness are met and base saturation data are not available, these are supposed to be mutually exclusive.

  *	Use of surrogate data is a separate, important issue that needs to be dealt with all the time in routine soil survey – and I think there is room to develop standards and guidelines for how that is done when the goal is supporting classification. However, this reviewer believes that these models and relationships should be developed on a local basis and not formally encoded in Soil Taxonomy unless they are "universal"

  *	The net effect of surrogates is short circuiting the intended logic of the Keys in lieu of data – which ultimately detracts from later efforts to improve the Keys. This especially is an issue where the surrogates could lead to inconsistent results with historic meanings, or depending on the lab/field method used, or in presence of optional/missing data with an OR operator in the key logic. The case of having all three possible measurements and them not “agreeing” with one another is another possible wrinkle. I presume base saturation would take precedence if you had it.

  *	I think the secondary carbonates criterion is OK, but worry about the possible effects of recent liming + lack of equilibrium on effervescence?  

## Rule 5
  
  * My preference for this simplification proposal would be towards simpler statements that reflect essentially the same meaning – rather than just abandoning criteria.

## Rule 6 

  * I support the intent of the proposed minimum thickness changes – I think the criteria are too complicated as is. I don’t like minimum thickness depending on variably on subsurface diagnostic features or on their bottom depths (e.g. Argillic bottom depth) -- this winds up being problematic for a variety of reasons related to data quality at depth.

    *	That said, it is likely that the increase of thickness requirement will split some existing series definitions – not necessarily in a “meaningful” way in terms of mapping. 

    *	Many Xerolls have low-end ranges in thickness of their mollic materials around 18-20cm. Two to three inches (difference from 25cm) is more than just a round off difference that can be swept under the rug. The low end RIC are in part driven by existing taxonomic limits/concepts, unit conversion, assumed plow layer thickness etc. but is also reflected in the pedon data.
    
    *	For each series/components spanning the new thickness threshold a decision would need to be made about taxon placement – theoretically with some of the supporting pedons being re-correlated if needed.

  *	Marginal Mollisols (that don’t range much/at all beyond 25cm thick epipedon) would become Alfisols, Inceptisols, Entisols, etc. based on dominant condition type logic – this might be quite common in my area of the world with the few true Mollisols on the high end of RIC being non-limiting, similar soil inclusions when you consider their areal extent

  *	Conversely, soils that tend to have thicker-than-25 mollic materials would be Mollisols, possibly with a couple inches on lower-end series RIC truncated.

## Rule 7 

 * I support the idea of allowing Mollic epipedons in Aridic SMR if that is how this criterion has been historically interpreted. This may mean that you can irrigate your way into the Mollisols, by providing moisture for net primary productivity where the growing season normally would not have had adequate moisture. 
 * Considering that the criteria for moisture content of soil materials operates on the subhorizons of the epipedon, rather than the soil moisture control section (which may differ somewhat from the epipedon boundaries) it is rare that this criterion would be applied in the presence of adequate site specific data.
 
 * The criterion may have historic value, but it probably is and has been routinely bypassed. I am not aware of any viable way to systematically evaluate where/whether this criterion has been used as the data elements involved are not / have not historically been reported at a level of disaggregation necessary to make this specific taxonomic evaluation.

## Rule 8 

  * I am not sure what the intent of the wording/justification for criterion 1e is. 

  *	Were authors intending to propose an alternate definition of “fluidity”? 

  *	We have Fluidity Class (in Field Book for Describing and Sampling Soils, pages 2-65 and 2-105). 

  *	I can’t really comment from experience on the relative utility of n value versus Fluidity Class – I have never "measured" the n value. Just used the common guidelines.

  *	Suggestion: replace criterion with _Fluidity Class is non-fluid_ to achieve the desired effect using existing standards
  
## Other notes

 *	"component horizon or layer" = "subhorizon" (semantics)

 *	Footnote 1: this footnote needs to be clarified
 
 * So, properties of upper 18cm are still relevant for water/wind/HTM? Or should this mixed thickness be 25cm to match the minimum thickness? 
  
 * Also, "weighted average sample" – depth weighted average? Volume weighted average (I.e accounting for bulk density)? "as if" it were physically mixed? Is this mathematical or physical mixing? – and what are the weights?
  
 * I support the mathematical mixing – but it has its problems when the overlying or underlying material would not meet mollic on its own.
  
   - Personally, I question the value of mixing of non-mollic and mollic materials to result in a positive mollic determination. Do we really need to include these cases in mollic epipedon? It is important for historic purposes to ensure same classification of agricultural and non-agricultural usage of same "soil type," but in my mind it seems it has potential to dilute the Mollic concept and/or be abused to make more Mollisols in floodplains.
   
   - At a minimum, the reasoning behind this footnote should be expanded on in the revised proposal. 
   
   - I think we could exclude recent deposits up to a certain (thin) thickness from evaluation for epipedon criteria. Beyond that point we need to ask ourselves if we have something that is more like a Mollic *fluvents/Fluvaquents in that geomorphic position. 
   
   - Technically, stratification or rock structure of the recently deposited material precludes an epipedon, and where a surface is buried you have criteria for Fluventic/Cumulic irregular carbon distribution with increasing depth. Just because you mix away the evidence of this doesn't change the geologic evidence of how that material got there; in an undisturbed case it would be described differently than after tillage.

 * Footnote 2: The only method for determination of base saturation for Mollic epipedon is the base saturation based on CEC and extractable cations in ammonium acetate at pH 7. 
 
   - What "laboratory analysis by proximal sensors in the field" is approved for this purpose?
 
 * Footnote 3: I recognize the potential value of harmonizing the strange handling of possible (lack of) Mollic epipedons in Albolls – but it does not have a place in this “simplifying” proposal. 

   - The proposed change mirrors the criteria for Albolls, which are allowed to have horizons that would be a Mollic epipedon if it were not for an Albic Horizon within 18 cm. Albic could be as thin as 1cm, per definition. Seems like the thickness requirement is only relevant to Albolls suborder, so we don’t need it in the Mollic Epipedon definition. 
