# Proposed Revisons of C and R Master Horizons, r and d horizon suffixes, and Densic, Paralithic, and Lithic Materials/Contacts
(2/18/20; PDF; 143 KB)

## Recommendation

**Recommendation:** Reject both proposals (2020/04/21) 

Reject both proposals. None of the proposed changes are necessary – and there is no single clear proposal to even review here. There is room for clarifying existing definition of root-limiting layer versus the general concept of “root-restrictive” – since clearly there is much confusion – but the proposals do not offer any clarity. More concerning, their solutions seem likely to add to existing confusion, rather than reduce it. 

## Selected quotes

> “There is a question where the regolith is thick and the soil scientist stops at two meters and the geologist starts at 50 meters - who's field is this one in between?” 
> – Guy Smith, ‘1.1 Definition of Soil’, Guy Smith Interviews, p. 2

> “We use diagnostic horizons in Soil Taxonomy rather than the traditional letter designations because the letter designations of A, B, and C to which we add suffixes like t, or e, or what have you, make it impossible to avoid the use of A, B. and C considerations in the taxonomy.”
> – Guy Smith, ‘1.6 Basic Principles of Soil Taxonomy’, Guy Smith Interviews, p. 21

> “The use of a suffix symbol is not restricted only to those horizons and other criteria as defined in Soil Taxonomy.” 
> – Keys to Soil Taxonomy, 12th edition, p. 337

## Concepts in Soil Taxonomy

**NOTE: I use the "cementation" term, but am aware that the replacement for this term ("coherence") has been accepted as a change to our national standard. This document uses _cementation_, which refers to a standard set of classes and method familiar to most field soil scientists. Cementation is the term still used in most standards in wide circulation.**

Horizons and layers that are root-restrictive commonly coincide with diagnostic features that imply a root-limiting layer (Keys to Soil Taxonomy, 12th edition, p. 319). Currently root-restriction as a general concept is not defined in one place in NCSS standards. Rather it is portrayed in a relative sense (within a pedon/polypedon) using a combination of horizon designations and/or diagnostic materials which imply varying degrees of restriction to root entry into the matrix.

A Cr or Cd horizon is intended to be a root-limiting layer if the upper boundary of that horizon coincides with a paralithic or densic contact. All paralithic or densic contacts coincide with the top depth of a Cr or Cd horizon. However, the inverse is often, but not always, true. This is because the uppermost boundary of paralithic or densic materials may not be a contact. If there is no a contact, there is no root-limiting layer. 

A horizon with a d suffix implies physical root-restriction, without any implications about parent material kind, crack spacing or a root-limiting layer. Use of d suffix is not “wrong” if it is used to depict relative “physical root-restriction” coupled with “non-cemented” cementation class. If the criteria for densic contact/materials are adhered to in determining depth to a root-limiting layer, decision to use or not use d in a field description will not affect taxonomy or interpretations. A horizon with r suffix implies soft or weathered bedrock, with a specific cementation class. But is not limited to specific bedrock kinds or crack spacings.

Densic materials, paralithic materials, and the materials below a lithic contact have in their definition root-restriction to “only cracks.” The materials are separated based on their cementation class. Using cementation, there is no conceptual overlap between the corresponding diagnostic features for the purposes of Soil Taxonomy. In these materials, there is also no specific implication of a root-limiting layer, but root-restriction is implied because roots exist only in cracks.

The cementation class of a layer is determined by a defined method. Air-dry fragments of the right size are placed in water for 1 hour. If they do not slake, they are cemented, and their resistance to rupture following an applied force is measured. In practice, in areas with less-well-cemented to noncemented bedrock/sediment, these observations can be made routinely from air-dry correlation box samples and are used to develop working models for dominant conditions of various soil forming factors within a survey extent. While determination of exact cementation class for layers and profiles may vary somewhat, general patterns do exist that are enough to distinguish between non-cemented, and less versus more than moderately cemented – sufficient for assigning the relevant restrictions for calculation of e.g. T factor.

## Proposed criteria not related to soil properties

Some proposed criteria are objectionable due to relying on inferences not related to soil properties. This comment is specifically addressing the strong points made about limiting Cd to “Quaternary” deposits or certain classes of parent materials – such as the ones given in examples in the Keys for densic/paralithic materials or the different horizon designations.

Based on this line of reasoning, I think the example parent materials that are currently included after the definitions of in the Keys should be removed. They have potential to be misconstrued as _the_ definition, rather than examples. It seems that these proposal authors made that error.

Parent materials, specific origins, etc. get connected to genetic horizon designations in people’s minds -- but no universal connection between diagnostic features and parent material kind exists. Some genetic horizons and suffixes are associated with general groups of parent materials – organic materials, limnic materials, water, bedrock etc. – but these are broad categories that have dramatically different properties that are for the most part easily discernible. They do not invoke specific interpretations about age/origin that cannot be determined from within a pit by a trained soil scientist.

Time since deposition or emplacement does not necessarily coincide with how weathered an exposure is, how that exposure weathers, or if it remains consolidated. In certain systems rocks/sediments have been deposited, buried, consolidated, re-exposed, eroded, re-buried etc. From the soil’s perspective, how “old” is the outer surface of the rock that we expose at the bottom of our soil profile? Soil horizon designation should not be reduced to an overlay of location on a geologic map and cross referencing to a table of theoretical ages or classes – essentially a categorical (non-soil) map of the world where various soil designations are “allowed” and where they are not. 

### "relatively unaltered"

While I don’t find I have a use for Cd on bedrock in my area – and have even “argued against” use of Cd in favor of more-cemented Cr – I am very cautious of adding new limitations on the usage of d where they are not needed. _Bedrock, densic_ is an option as a restriction in NASIS for where non-cemented densic materials are present in bedrock-derived layers that impose a densic contact. 

Based on my experience on highly weathered bedrock of the Sierra Nevada Foothills, non-cemented weathered bedrock usually does not meet the criteria in densic materials for “relatively unaltered [by pedogenesis]” if one looks carefully. In some paralithic materials we probably stretch the definition of “relatively unaltered” for practical purposes. This is likely not the case in many systems, but if you have significant pedogenesis in the matrix, d is allowed as a designation, but none of the densic or paralithic diagnostic features (which require “relatively unaltered materials”) are technically available. In such cases, use or non-use of d or r would be a moot point taxonomically speaking – denoting only root-restriction or cementation of the materials, respectively – which are not diagnostic of anything in and of themselves – and have no direct effect on the root-limiting layer. 

## NASIS/SSURGO perspective

In NASIS/SSURGO, the effect of high density that is not associated with a densic contact/materials can be captured by populating higher values for those d (or non-d) layers at the Pedon/Component Horizon level and/or assigning different representative structure (e.g. platy, massive) as appropriate. We don’t typically consider the rock or pararock fragments in the soil profile to be “root-restrictive,” per se, though they certainly impose structure on the arrangement of soil materials. Unfortunately, in NASIS/SSURGO we have limited options to depict presence of weathered rock structure that no longer is cemented, but also may influence root distribution. So, one or more new “rock structure” type choices in Component/Pedon Horizon Structure to complement use of “massive” or  “single grained” would help ease the pain of calling non-cemented, weathered bedrock C, where conceptually it might seem to fit better with Cr because of its origin and relationship to underlying layers – or even with Cd because of describer’s interpretation of relative physical root-restriction imposed by rock fabric. There were no such suggestions of novel material properties or determinations to help “resolve” this apparent issue in either proposal.

## A counter-proposal based on existing standards

Basic guide to identification of root-limiting layers in terms of master horizons, horizon suffixes, and diagnostic materials/features 

### Root-Limiting Layer

A root-limiting layer defines the bottom of the soil horizons considered for most, but not all, differentia at the family level (Keys to Soil Taxonomy, 12th edition, p. 319). The upper boundary of a root-limiting layer coincides with the upper boundary of the following diagnostic features: 

 - duripan, fragipan
 
 - petrocalcic, petrogypsic, placic horizons
 
 - (continuous) ortstein
 
 - densic, lithic, paralithic, petroferric, or manufactured layer contacts

All diagnostic horizons and features listed above have their own specific language of what constitutes root “limitation.” 

All (except for fragipan) pertain to a spacing of cracks/fractures where roots can enter of 10 cm or greater. Some have additional criteria for cementation and/or statements about lateral continuity.

### Horizon designations (field interpretation): 

 - R - strongly cemented to indurated bedrock; “generally” cracks roots enter are widely spaced

 - Cr - extremely weakly to moderately cemented bedrock; crack spacing may be much <10cm

 - *d - physically root-restrictive

 - *m - >90% pedogenic cementation (>extremely weakly), physically root-restrictive

### Tabular Guide

```{r, echo=FALSE}
dat <- read.table(header = TRUE, text =
  "'Feature or Material'	'RootLimitingLayer'	'CracksGT10cm'	'MIN'	'MAX'	'RootRestrictive'
  'A, E, B, C (no r / d)'	NO	NO	NONE	NONE	NO
  R	NO	NO	ST	I	GENERALLY
  Cr	NO	NO	EW	M	NO
  *d	NO	NO	NONE	NONE	YES
  'Lithic contact'	YES	YES	ST	I	YES
  'Paralithic contact'	YES	YES	EW	M	YES
  'Paralithic materials'	NO	NO	EW	M	YES
  'Densic contact'	YES	YES	NONE	NONE	YES
  'Densic materials'	NO	NO	NONE	NONE	YES
  'Duripan'	YES	YES	EW	I	YES
  *qm	NO	NO	EW	I	YES
  Fragipan	YES	NO	NONE	NONE	YES
  *x	NO	NO	NONE	NONE	YES")
knitr::kable(dat, caption = "Guideline to root-limiting layers, evidence of root-limitation, cementation and root-restriction for various genetic horizons, diagnostic horizons, features and materials.")
```

### Existing Definitions

 - Cr is root-restrictive when it coincides with paralithic materials – which restrict roots to “only cracks” – but is only a root-limiting layer if those cracks are far enough apart.
 
 - Cd always denotes physical root-restriction, is not used on cemented materials, and is not necessarily a root-limiting layer unless cracks where roots can enter are >10cm apart.
 
 - *m is physically root-restrictive due to a pedogenic process but does not explicitly imply a root-limiting layer. It is more specific about volume of cementation than r. There are instances where an m could be used that would not be a root-limiting layer per Soil Taxonomy e.g. horizon cemented >90% with salts more soluble than gypsum: zm 
 
 - Paralithic/densic materials imply root-restriction and “relatively unaltered [by pedogenesis]”. Either could occur above a paralithic or densic contact. 

## On an explicit definition for “root-restriction”

We could explicitly define “root-restriction” (by some measure, say bulk density) as a lesser limitation relative to the root-limiting layer – and then require that for the use of d. But, I think greater flexibility is offered to the field soil scientist with the existing definition of d implying simply “non-cemented, physically root restrictive” with no parent material connotations or specific quantification of how restrictive – which is pretty subjective and dependent on relative local conditions.

## How to handle weathered bedrock that is root-restrictive but non-cemented: 

If bedrock is non-cemented, it does not meet the cementation criteria for paralithic materials or the Cr designation. If it does not exhibit pedogenic alteration, you should designate it C or Cd because it is non-cemented parent material – your choice as describer depends on your interpretation of relative root-restriction within the profile and within the landscape.

## Identifying the root-limiting layer in weathered bedrock
If roots appear to have a regular, closely spaced, distribution into a fresh exposure of the upper boundary of weathered bedrock material, then there is no evidence for a root-limiting layer. If roots are absent, the assessment needs to be based on “distance between cracks where roots can enter,” and it is up to the describer to infer where/if a root-limiting layer occurs. Some layers could have >90% bedrock fragments and in lieu texture of “parachanners” “paragravel” or similar -- but cracks and included soil materials commonly have or could have roots. 

Technically, the horizon designation should be based on the soil material “in the fractures” – so your ability to manage getting a sample to texture and inspect in the field will probably guide you to an appropriate designation – don’t overthink it. This is often where one should find Cd is an inappropriate choice of designation. How much soil material, if any, you manage to get from the fractures is dependent on local nature of bedrock: composition, fracture pattern etc. 

Observations made with an auger or other drilling device are going to disrupt fabric of the soil and rock, and will interfere with assessments of depth, cementation and arrangement of cracks – and also offer limited evidence if any of rooting patterns – so the describer needs to be calibrated to the nature of local materials exposed in real pits if they intend to interpret auger borings for distinguishing certain contacts. You could be well below the upper boundary of in situ weathered bedrock before you find cementation in a pit -- whereas augers can be quite effective at grinding up more weakly cemented material. 


## On designations of soil material between rock / pararock fragments in parent material layers

### C

C expresses properties that indicate the soil material is related to the underlying parent bedrock materials – but lacks pedogenesis, cementation and physical root-restriction. It does not imply a root limiting layer – and is considered part of the soil for classification purposes if within series control section.

### Cd

Cd implies physical root-restriction without cementation. Cd horizon only contains densic materials if the “bulk density or organization is such that the roots cannot enter, except in cracks.” Densic materials have a densic contact at the depth where cracks are >10cm apart. A Cd horizon could contain soil materials dense enough to restrict, but not entirely prevent, root entry into the matrix. The definition of a densic contact or statements about distance between cracks where roots can enter is rightly not invoked in definition of d suffix even though d explicitly implies some physical root-restriction. 

### Cr

Cr implies weathered or soft bedrock with cementation class extremely weak to moderate. There should not be significant amounts of soil material below/within a Cr horizon, except in fractures – though I have seen Cr used in combination with soil horizons with a virgule (e.g  BCt / Cr) in extreme cases – such a construct is hard to interpret over. A Cr horizon contains paralithic materials when roots cannot enter the cemented materials, except in cracks. The upper boundary of a Cr layer usually is, but doesn’t have to be, a root-limiting layer. The implication of a root-limiting layer comes from assignment of a paralithic contact—which has the specific criterion about minimum spacing of cracks where roots can enter greater than 10cm.

### All horizon designations

For all horizon designations: The mechanism one infers for how material got to be that way is not really part assigning a designation – the designation should reflect the describer’s interpretation of soil (or non-soil) properties observable in the field. Horizon separations should at a minimum reflect the major breaks needed for the properties you can identify as important for interpretations. However, the horizon designations themselves do not carry any taxonomic weight.

For example: there are many ways in which argillic horizons can accumulate clay. In general terms, we often suggest the mechanism is lessivage -- that clay is vertically translocated in the profile. Many argillics form in part by this process, but we don’t make the process itself a distinction for the t subscript. Any evidence of pedogenic clay accumulation is enough to give it a t. If the bulk of the clay increase is due to in situ weathering, our interpretations of soil descriptions do not suffer because we thought it was lessivage in the field. For taxonomy, if the properties for an argillic horizon are met, then there is an argillic. 

Guy Smith provides a good example involving Bt horizons and lamellae not necessarily constituting an argillic ‘1.6 Basic Principles of Soil Taxonomy’, Guy Smith Interviews, p. 21. Likewise, with a d, we don’t assign any value to the process or specific parent material that “caused” it to be a d, what matters for interpretations is that it is a physical root-restriction. If that root-restriction is enough to warrant a densic contact and a root-limiting layer, then those features are assigned, and taxonomy will reflect it.

While it is a helpful validation to compare diagnostics, restrictions and genetic horizon labels/depths – as they should generally coincide – there is no need to encode a requirement that morphologic and diagnostic horizons match within Soil Taxonomy. 

## On improving systems for describing the lower boundary of soil

As the Keys to Soil Taxonomy say “the lower boundary that separates soil from the nonsoil underneath is most difficult to define” (p. 1) – so, in my opinion, this debate is a worthy endeavor – but we must remember the object of our study (the soil). I think there are opportunities to recognize pedogenesis where we perhaps traditionally have not, and that plays into future decisions about how to describe these soils. Dealing with the progression of “level of detail” in describing contacts over the last century of soil survey will be an ongoing problem for update work.

Non-cemented bedrock materials in my area I typically designate as master horizon CB, BC or C depending on their specific properties. Usually these layers are not root-limiting – but are bedrock “rind” layers could have important pedogenic features – redoximorphic features, dense arrangement, odd texture, parafragments, etc. that are influenced by the underlying contact, as well as soil processes, – and rightly should be included above the contact to consider their effects on soil interpretations – rather than just as a gradual boundary that exists at the contact. I feel the same about Cd/densics that we have in the mountains. These lower gradational horizons commonly overlie a paralithic contact which, by prevailing convention, essentially always coincides with the top depth of shallowest Cr.

In the Southwest Region, we have only just begun to compete series on portions of the series control section below a paralithic contact – and as we have got more detailed about those criteria, I have seen some patterns emerging in the data for the lowest reaches of the subsoil for certain components. I need to provide specific justification for components if my restrictions / diagnostics / horizon depths don’t line up. I expect I may only get more detailed in my approach to this problem of “describing the lower boundary of the soil” over my career. 

 While there are cases where I could imagine having my diagnostics and morphologic horizons deviate from the prevailing norm (i.e. Cr without a paralithic contact) I have never felt the need or justification to do so in a SSURGO component. 
 
Cd over Cr to portray densic bedrock over paralithic bedrock is technically a legitimate option I could use to portray a gradient in bedrock weathering. Likewise, I could in theory use it for dense till over bedrock – with or without densic or paralithic _contacts_. Those two cases would be distinguished by parent material -- and taxonomically they could be identical if those parent materials did not result in meaningful differences in the taxonomic relevant quantities.

### On bedrock age

There seems to be a lot of unnecessary concern about the use of Cd on “older” bedrock but I see no harm in it being available for use. I imagine it being useful for detailed descriptions on just about any less-consolidated / less-fractured, relatively [pedogenically] unaltered, bedrock or sediments. In general, I personally have avoided Cd on bedrock – but it has been suggested to me as an option in the past. 

An explanation why I don’t use it is based on the rocks commonly found in my area – which are highly fractured – significantly influencing weathering patterns and potential pedogenesis. If a layer containing non-cemented bedrock is so weathered that it no longer reflects original volumetric relationships in the parent rock (i.e. the visible rock fabric has become “denser,” or large portions have been altered/removed, but elements of it are still present) it has generally weathered enough,  to be considered a soil material (rather than parent material) in the profile proper. It may locally contain significant amounts of pararock fragments, but it is too pedogenically altered and too penetrable by roots to be “densic materials” or “paralithic materials” per their definitions.

There are volumes primarily of highly weathered soil material mixed with non-cemented in-situ weathered rock, cemented rock, clay films on various surfaces, etc. In the field, I usually assume that roots can get into/through such non-cemented, pedogenically altered bedrock layers when there is water to be had — so I treat them as soil horizons, and have no contact above that depth. I commonly have evidence of roots present in enough quantity up to the actual contact.

### Densic materials that are not relatively dense

The case allowed in densic materials, where non-cemented material does not have to be “dense” but only “resistant,” is unusual to me. It sounds like it is intended to account for something more like a “strongly contrasting density” rather than “dense”– but both are included within one “material” definition. The argument in favor of this is that the net result of either case a common criterion: root-restriction to just cracks (and, in most cases, also a root-limiting layer where those cracks are far enough apart). If the diagnostic features for a soil reflect the presence/absence of root-limiting layers that are needed for classification, I have no problem with whatever the horizon designations may be in the field.

### On the concept of cracks or fractures in weathered granitoid grus

Having many-meters thick materials, without lithic, paralithic and/or densic contacts is real phenomenon on some areas of deeply weathered granitoid bedrock of the Sierra Nevada – per Dr. O’Geen’s commentary. 

In my opinion, the concept of a “crack” or “fracture” is truly ill defined for the purposes of granitoid “grus.” - as well as probably many other types of rocks that have planes of weakness. These rocks have plenty of macroscopic fractures in them – but also due to their mineral composition (e.g. mica weathering to vermiculite) also exhibit extensive grain-scale “fracturing,” making them inherently more penetrable to water and roots than their un-weathered counterparts -- further compounding the weathering process.

While interesting, and relevant to land use and management in these forested areas of the Sierra Nevada that in some cases have  experienced significant tree mortality and fire the greater depths are [presently] beyond the scope of Soil Taxonomy and routine soil survey. 

### Extending the series control section, optional phase criteria?

The series control section extends 25cm beyond a paralithic or densic contact, or about 200 cm, whichever is shallower. 

There is probably an opportunity for capturing deeper vadose zone features in e.g. optional family level classes and/or special extensions to the series control section, or a new "phase control section" as well as perhaps new horizon designations -- rather than confusing re-statements of existing concepts.
