# Tier Criteria and Control Section Depth for Organic Soils, Reaction Classes for the Family Differentiae for Organic Soils, Definitions and Criteria of Soil Organic Material Types 

Tier Criteria and Control Section Depth for Organic Soils: [(2/18/20; PDF; 143 KB)](https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcseprd1546022&ext=pdf)

Reaction Classes for the Family Differentiae for Organic Soils: [(2/18/20; PDF; 373 KB)](https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcseprd1546021&ext=pdf)

Definitions and Criteria of Soil Organic Material Types: [(2/18/20; PDF; 328 KB)](https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcseprd1546020&ext=pdf)

## Recommendation

Recommendation: Return to author. (2020/06/19)

The author highlights the arbitrary division of control section concepts for Histosols and Histels based on moss fiber content and or bulk density <0.1g/cc. While these criteria historically had a clear intent, they can be challenging to evaluate in the field – and even more challenging to evaluate for database records where important information about soil composition/fabric may be missing. 

The author proposes:

 - eliminating the “bottom tier,” 
 
 - uniform 0 - 60cm interval for the “surface tier”
 
 - control section bottom depths uniform at 130cm – implying a “subsurface tier” from 60 to 130cm (or other limit on depth).
 
I think that there is a need for clarifying logic currently found on p 25 and 26 in KST 12th edition – which is difficult to follow. Even if these proposals are not accepted as-is, I hope that the author can contribute some better wording for the new version of the keys to enhance consistency of application of current criteria.

I generally support the elimination of fiber-based criteria for the control section, as we already have taxa at a higher level in the Keys (e.g. Sphagnofibrists) that capture the more-extreme cases of these soils – so capturing it again in the family / control section keys seems somewhat redundant. 

## More examples needed

That said, I think we need more examples and information of how these will affect existing series concepts/mapping and separation of distinct taxonomic concepts at higher order. Unfortunately, data on Histosols is affected by historic priorities that the author identified in proposal.

## Impacts on Region 2 NASIS Pedons

I started off by pulling all the Histosol descriptions we have in NASIS for Region 2. I wrote a calculation evaluate whether the 30cm or 60cm surface tier depth will apply for each profile. 

The key property of interest to surface tier determination is fibric soil materials. As the author mentions, it is challenging to evaluate “moss fiber content” and bulk density -- and those determinations are prone to some error/subjectivity. 

For a soil to have the 60cm thick surface tier under old rules, it must be fibric throughout all soil horizons in that 0 - 60cm depth – and >75% of those organic fibers must be moss or have bulk density < 0.1 g/cc. This means that based on fibric materials alone we can estimate an upper boundary of effects of changing surface tier criteria. We will identify fibric by simply looking for lieutex of “spm” or “peat” or an “i” suffix in horizon designations in upper 60cm. If the horizons are not fibric, the composition of fibers and density are irrelevant. They will not get the Sphagno* control section. 

What I found is that some 85% (n = 230) of Histosols in NASIS for R02 currently use the 30cm surface tier depth. Therefore, under this proposal, these soils would see a thickening of their surface tier to 60cm. This is, to me, more of a “problem” than changing the control section bottom depth from 160 to 130cm or eliminating bottom tier. The near-surface properties strike me as more important, inherently, and this is corroborated by the authors suggestions about typical rooting depth etc. It seems that more consideration is needed to see whether it is acceptable for all “non-Sphagno” Histosols to have double the surface tier thickness. 

At first blush this proposal appears to introduce a “simplification” for relatively rare or localized Sphagno soils – but it winds up having a disproportionate effect on everything else in the Histosols by increasing the surface tier thickness. Retaining 30cm would be more consistent with historic taxonomy – but it seems that the author was in favor of 60cm based on native plant rooting depths. I don’t dispute that as valid logic – it is just different from what we are doing “most” of the time. [EDIT: This is actually rarely diagnostic or required series criteria, per Dan Wing's comments to the committee]

Approximately 12% (n = 33) of R02 Histosols have a control section bottom depth of 160cm. In approximately 30% (n = 189) of R02 Histosols, a root-limiting layer is present that truncates the control section to a depth less than 130cm. Therefore, the bottom depth of control section is less affected by this proposal than the surface tier bottom depth in R02.

In most R02 Histosols the surface tier will be doubling in thickness. However determination of reaction class would be limited to just the surface tier, as opposed to whole control section. This will potentially lead to changes in series concepts but reduces the thickness of materials that are relevant to determining organic soil reaction class – bringing those materials closer to surface. This should both make data collection / inference easier as well as, hypothetically, taxonomic changes more relevant to interpretations. I think that the potential benefits of the simplifications proposed here potentially outweigh the issues that typically will come with redefining a control section. Unlike particle size control sections for mineral soils, the Histosol tier depths were “arbitrary” and not dramatically affected by specific diagnostic feature depths. However, the minimal amount of historic data / focus on these soils dramatically complicates their potential re-correlation. If we are to collect more data on these soils, as I think we will… it might be good to get these concepts figured out before that due to the implications for sampling protocol.

## Question: about replacing subsurface tier

It isn’t made clear how the subsurface tier related criteria in the various Histosols keys would be replaced with a single depth of 100cm. Or why 100cm? Further, I am not sure why the subsurface tier needs to be removed from these criteria. It seems a now-more-consistent concept of a subsurface tier should still be used on p167, p171, p 172 etc.

The subsurface tier would be the portion of the control section below 60cm and above 130cm (or RLL). An evaluation at a single depth (100cm; intersects only one horizon) is different from an evaluation over an interval (i.e. evaluate all layers within the subsurface tier), and 100cm is a foot or more shallower than historic criteria that may be meaningful (e.g. occurrence of mineral soil material within subsurface tier). 
Why have the control section to 130cm, if we will use 100cm in the key? If you want those evaluations to only go to 100cm (I could imagine practical reasons why) then why not propose that we limit the control section too? I pretty sure I would NOT support that – but regardless, 100cm needs more justification considering the rest of proposal.

## Comments on reaction class
I broadly support separating calcareous fens from euic/dysic – but I think some of the other criteria in that proposal need work. That work is dependent on how this proposal is re-structured.

## Final comments

I support the spirit of these changes – with the caveat that there may be significant changes in the surface tier thickness that may cause correlation issues. However, per Dan Wing's clarification, he reviewed all series correlated the Histosols and did not encounter cases where this would cause significant conflict with the range in characteristics.

There probably are “issues” with our current taxonomic model for Histosols that we can inform with modern analyses – and make future work more productive. The specific effects on mapping/taxa cannot be evaluated based on this proposal alone – as simultaneous changes to reaction class have been proposed -- and the data available to support some of these concepts in the databases are sparse.



